"""Interactive setup: prompt for the few fields that need user input and
write a config.yaml. Triggered via `python -m scanner --init`.

Deliberately small. It only asks for the things the user *must* fill in
(addresses, webhook). Everything else falls back to the documented
defaults — quiet hours, retailers list, polling cadence — which the user
can edit in the generated file. The goal is "go from clone -> working
scanner in 60 seconds" without forcing anyone through a 20-question
questionnaire."""
from __future__ import annotations

import sys
from pathlib import Path
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

from .config import CONFIG_PATH


TEMPLATE = """\
# Generated by `python -m scanner --init`. Edit freely.
locations:
  home: "{home}"
  work: "{work}"

route_radius_miles: {radius}

routing:
  engine: osrm
  google_api_key: ""

timezone: {timezone}

retailers:
  target:        {{ enabled: true }}
  walmart:       {{ enabled: true }}
  bestbuy:       {{ enabled: {bestbuy_enabled}, api_key: "${{BESTBUY_API_KEY:-{bestbuy_key}}}" }}
  pokemoncenter: {{ enabled: true }}
  gamestop:      {{ enabled: true }}
  costco:        {{ enabled: false }}
  samsclub:      {{ enabled: false }}

poll_interval_seconds: 180
heartbeat_seconds: 21600

quiet_hours:
  start: "{quiet_start}"
  end:   "{quiet_end}"

discord_webhook: "{discord}"
ntfy_topic: "{ntfy}"

products: all_sealed
"""


def _ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    raw = input(f"{prompt}{suffix}: ").strip()
    return raw or default


def _ask_yes_no(prompt: str, default: bool = False) -> bool:
    d = "Y/n" if default else "y/N"
    raw = input(f"{prompt} [{d}]: ").strip().lower()
    if not raw:
        return default
    return raw.startswith("y")


def _ask_timezone() -> str:
    """Loop until we get something zoneinfo accepts."""
    while True:
        tz = _ask("Local time zone (IANA, e.g. America/Chicago)", "America/Chicago")
        try:
            ZoneInfo(tz)
            return tz
        except ZoneInfoNotFoundError:
            print(f"  ! {tz!r} is not a valid IANA timezone. Try again.")


def run(target_path: Path = CONFIG_PATH, *, stdin=None) -> int:
    """Walk the user through filling config.yaml. Returns shell exit code."""
    global input  # allow tests to swap stdin
    if stdin is not None:
        # Replace built-in input() with a generator-backed callable.
        replies = iter(stdin)
        input = lambda _p="": next(replies)  # noqa: E731

    print("Pokémon TCG scanner — setup wizard")
    print("Press Enter to accept the default in [brackets].")
    print()

    if target_path.exists():
        ow = _ask_yes_no(f"{target_path} already exists. Overwrite?", default=False)
        if not ow:
            print("Aborted.")
            return 1

    home = _ask("Home address (street, city, state)")
    while not home:
        home = _ask("Home address (required)")
    work = _ask("Work address (street, city, state)")
    while not work:
        work = _ask("Work address (required)")

    radius = _ask("Route radius in miles", "4")
    timezone = _ask_timezone()
    discord = _ask("Discord webhook URL (Enter to skip — console-only)", "")
    ntfy = _ask("ntfy topic for mobile push (Enter to skip)", "")

    bestbuy = _ask_yes_no("Enable Best Buy now? (needs free API key)", default=False)
    bestbuy_key = ""
    if bestbuy:
        bestbuy_key = _ask("  Best Buy API key (leave blank to set via env)", "")

    quiet_on = _ask_yes_no("Suppress non-must_have alerts overnight?", default=True)
    quiet_start = "23:00" if quiet_on else ""
    quiet_end = "07:00" if quiet_on else ""

    rendered = TEMPLATE.format(
        home=home,
        work=work,
        radius=radius,
        timezone=timezone,
        bestbuy_enabled=str(bestbuy).lower(),
        bestbuy_key=bestbuy_key,
        quiet_start=quiet_start,
        quiet_end=quiet_end,
        discord=discord,
        ntfy=ntfy,
    )

    target_path.write_text(rendered)
    print(f"\nWrote {target_path}")
    print("Next: `python -m scanner --check-config` then `python -m scanner --dry-run`.")
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(run())
